# Import BaseModel from Pydantic.
# Pydantic is used by FastAPi to define structured data models and 
# automatically validate API request data

from pydantic import BaseModel

# Import datetime so we can record when a payment trasction
# is created inside the system

from datetime import datetime

# Import Enum so we can define fixed sets of allowed values.
# We will use this for things likepayment status and payment channels.

from enum import Enum

# PaymentsStatus defines the lifecycle stages that a payment
# transaction goes through inside the platform
#
# Using Enum ensures that only valid status values can exist.
# This prevents invalid states from appearing in the system.

class PaymentStatus(str, Enum):
    
    # The payment request has been received by the API
    # but has not yet started processing
    
    CREATED = "CREATED"

    # A background woorker has started processing the payment

    PROCESSING = "PROCESSING"

    # The payment was successfully completed.

    SUCCEEDED = "SUCCEEDED"

    # The payment processing failed.

    FAILED = "FAILED"

    # The funds have been settled to the property owner

    SETTLED = "SETTLED"

    # PaymentChannel defines the method used by the tenant
    # to submit the rent payment
    #
    # Each payment channel may have different processing rules,
    # fee structure, and settlement timelines.

class PaymentChannel(str, Enum):
    
    # ACH bank transfer payment.
    # Typically involves bank processing and may take longer
    # to settle compared to card transaction.

    ACH = "ACH"

    # Credit or debit card payment.
    # Usually returns authorization results quickly
    # but may have higher processing fees

    CARD = "CARD"

    # Cash payment collected through an authorized retail 
    # payment agent

    CASH_AGENT = "CASH_AGENT"

# PaymentTransactionCreate represents the data required
#  when a tenant submits a payment request to the platform.
# 
# This model is used by the API layer to validate incoming
# payment requests before they enter the processing system.

class PaymentTransactionCreate(BaseModel):    

   # Identifier of the tenant making the payment.

   tenant_id: str

   # Identifier of the rental property for which the rent 
   # is being paid

   property_id: str

   # Identifier of the property owner who will eventually
   # receive settlement of the rent payment

   owner_id: str

   # Identifier of the rental manager reesponsible for 
   # managing the property and payment operations.

   rental_manager_id: str

   # Year for which the tenant is paying rent.
   # Example: 2026
   rent_year: int

   # Month for which the tenant is paying rent.
   # Value should represent a calendar month (1–12).
   # Example: 3 represents March.
    
   rent_month: int
    
    # Amount paid by the tenant.
    
   amount: float

   # Currency used by the transaction, e.g., USD

   currency: str

   # Payment channel used by the tenant.

   payment_channel: PaymentChannel

# PaymentTransaction represents the full transaction record   
# stored and processed by the payment platform
#
# This model includes the original request data and additional
# firlds generated by the system during processing.

class PaymentTransaction(BaseModel):

    # Unique identifier generated by the platform for each
    # transaction.

    transaction_id: str

    # Identifier of the tenant making the payment

    tenant_id: str

    # Identifier of the property associated with the tenant.

    property_id: str

    # Identifier of the property owner who will receive
    # settlement of the rent payment

    owner_id: str

    # Identifier of the rental manager responsible for
    # managing the property

    rental_manager_id: str

    # Year for which the tenant is paying rent.
    # Example: 2026
    
    rent_year: int

    # Month for which the tenant is paying rent.
    # Value should represent a calendar month (1–12).
    # Example: 3 represents March.
    
    rent_month: int

    # Amount paid by the tenant

    amount: float

    # Currency used for the transaction

    currency: str

    # Platform fee charged for processing the transaction

    platform_fee: float

    # Net amount that will be transferred to the property 
    # owner after deducting the plarform fee

    net_settlement_amount: float

    #  Payment channel used for the transaction.
    
    payment_channel: PaymentChannel

    # Current status of the transaction in the processing lifecycle.
    
    status: PaymentStatus

    # Timestamp recording when the transaction was created.
    created_at: datetime